### ISSUE TITLE
Nested Traffic Classification Policy

### ISSUE THREAD

**Issue by mattjhayes** [mattjhayes/nmeta#1]
Improve traffic classification policy functionality by adding support for multiple level hierarchy through ability to nest rules. 

Current Policy Example:
```
'PolicyRule 0':
    comment: OpenFlow Protocol Traffic
    match_type: any
    policy_conditions:
        tcp_src: 6633
        tcp_dst: 6633
    actions:
        set_qos_tag: QoS_treatment=system_priority
        set_desc_tag: description="OpenFlow Protocol Traffic"
```
Proposed Example:
```
'PolicyRule 0':
    comment: OpenFlow Protocol Traffic
    policy_conditions:
        match_type: any
        tcp_src: 6633
        tcp_dst: 6633
    actions:
        set_qos_tag: QoS_treatment=system_priority
        set_desc_tag: description="OpenFlow Protocol Traffic"
'PolicyRule 1':
    comment: Audit Division SSH traffic
    policy_conditions:
        match_type: all
        policy_conditions:
            match_type: any
            tcp_src: 22
            tcp_dst: 22
        policy_conditions:
            match_type: any
            identity_lldp_systemname_re: '.*\.audit\.example\.com'
    actions:
        set_qos_tag: QoS_treatment=high_priority
        set_desc_tag: description="High Priority Audit Division SSH Traffic"
```
The *match_type* attribute moves to within the *policy_conditions* clauses, and nesting of policy conditions is allowed
