### ISSUE TITLE
Time-Based Parental Controls

### ISSUE THREAD

**Issue by mattjhayes** [mattjhayes/nmeta#111]
**Name**: Time-Based Parental Controls

**Domains**: Home Network

**Use Cases**: Parental Control

**Value**: As a parent, I want to control the time my kids can spend on the Internet so they go to sleep at night by setting policy on the network that cuts off access for their devices after a particular hour of day. Additionally, it would be good to be able to set a maximum quota per day, and be able to whitelist educational sites from this restriction.  

**Works Today**: No

**Policy Snippet**:

``` YAML
---
tc_rules:
    # Traffic Classification Rulesets and Rules
    tc_ruleset_1:
        - comment: Restrict Kids Internet by Time of Day
          match_type: any
          conditions_list:
              - match_type: all
                identity_dhcp_hostname: kids_tablet
                time_of_day: 21:00-23:59,00:00-07:00
          actions:
              set_desc: "Drop kids tablet traffic when used outside allowed hours"
              drop: at_controller
```

To be resolved:
- Develop identity_dhcp_hostname classifier
- Develop time of day classifier
- Look into how a quota would work
- Would be useful to also identify who is using the device, but not sure how?
