### ISSUE TITLE
Geo-fence Parental Control

### ISSUE THREAD

**Issue by mattjhayes** [mattjhayes/nmeta#112]
**Name**: Geo-fence Parental Control

**Domains**: Home Network

**Use Cases**: Parental Control

**Value**: As a parent, I want to limit where my kids can use Wi-Fi gadgets to connect to the Internet, so that their surfing is done in public areas of the home, and can thus be better monitored.

**Works Today**: No

**Policy Snippet**:

``` YAML
---
tc_rules:
    # Traffic Classification Rulesets and Rules
    tc_ruleset_1:
        - comment: Restrict Kids Internet Access by Physical Location
          match_type: any
          conditions_list:
              - match_type: all
                identity_dhcp_hostname: kids_tablet
                location_geo: kids_bedroom
          actions:
              set_desc: "Drop kids tablet traffic when used in their bedroom"
              drop: at_controller
```

To be resolved:
- Develop identity_dhcp_hostname classifier
- Use network location to just restrict traffic to Internet?
- Develop geolocation classifier. How can nmeta receive geolocation data from Wi-Fi access points?
