### ISSUE TITLE
Policy Direction

### ISSUE THREAD

**Issue by mattjhayes** [mattjhayes/nmeta#35]
# Policy Direction

This issue sets an aspirational direction for nmeta policy, by specifying a future policy structure to work towards through use of an example policy. Separate issues will be raised to implement specific features to build toward this end-game.

## Considerations:
Operators of enterprise networks will want control over where traffic classification is run to maximise efficiency, i.e. run on a subset of interfaces on a subset of switches. They are also likely to want the ability to run multiple traffic classification policies, to suit differing purposes. This also improves efficiency by allowing use of smaller, more targeted policies.

Policy should also control what happens to packets and metadata post traffic-classification. This should include where the forwarding decision is made and what application makes it.
It is also desirable to have policy control of the collection of identity metadata. The set of ports (plus other criteria) where identity metadata is collected may differ from the locations where traffic classification occurs as some identity information is collected at the port to which a device is connected. Control should include port sets and types of metadata collected (i.e. MAC Addresses, LLDP, IP addresses, DNS resolutions etc)

## Principles: 
* Policy should start abstract and progressively get more detailed.
* Support ordering through means other than written order
* Less is more!
* Flexible enough so that could be used for more than just traffic classification

YAML supports lists, so these should be used for items that need order preserved, i.e. policy rules

Aspirational Policy Example:
```YAML
tc_policies:
    # Traffic Classification Policies:
    
    'Widget Dept Traffic Classification Policy':
        comment: Run traffic classification on Widget Department switch ports
        rule_set: widget_tc_rules
        port_set: widget_tc_ports
        
    'Guest Traffic Classification Policy':
        comment: Run traffic classification on guest access ports
        rule_set: guest_tc_rules
        port_set: guest_tc_ports

tc_rules:
    # Traffic Classification Rulesets and Rules
    widget_tc_rules:
        - 'PolicyRule 0':
            comment: Traffic from Non-Widget Devices (Identity Classifier)
            conditions:
                match_type: none
                identity_lldp_systemname_re: '.*\.widget\.example\.com'
            actions:
                set_qos_tag: QoS_treatment=low_priority
                set_desc_tag: description="Non-Widget Traffic"
        - 'PolicyRule 1':
            comment: Widget Intranet Traffic (Static Classifiers)
            conditions:
                match_type: any
                'conditions 0':
                    match_type: all
                    ip_dst: Widget_IP_Intranet_group
                    tcp_dst: 443
                'conditions 1':
                    match_type: all
                    ip_src: Widget_IP_Intranet_group
                    tcp_src: 443
            actions:
                set_qos_tag: QoS_treatment=high_priority
                set_desc_tag: description="Widget Intranet Traffic"
        - 'PolicyRule 2':
            comment: Widget Legacy App (Static and Payload Classifiers) 
            conditions:
                match_type: all
                conditions:
                - 'conditions 0':
                    match_type: any
                    tcp_src: Widget_Legacy_App_TCP_group
                    tcp_dst: Widget_Legacy_App_TCP_group
                - 'conditions 1':
                    match_type: all
                    payload_type: Widget_Legacy_App
            actions:
                set_qos_tag: QoS_treatment=high_priority
                set_desc_tag: description="Widget Legacy App Traffic"
        - 'PolicyRule 3':
            comment: Widget Statistical Mop-up (Statistical Classifier) 
            conditions:
                match_type: all
                statistical_qos_bandwidth_1: on
            actions:
                pass_return_tags: true

    guest_tc_rules:
        - 'PolicyRule 0':
            comment: Send non-example.com traffic via a proxy (Identity Classifier)
            conditions:
                match_type: all
                conditions:
                    - 'conditions 0':
                        match_type: any
                        tcp_dst: HTTP_TCP_group
                    - 'conditions 1':
                        match_type: none
                        identity_dns_re: '*.example\.com'
            actions:
                set_proxy_tag: 1
                set_desc_tag: description="Non-Example.com guest HTTP Traffic. Send to Internet via Proxy"
        
processing_rules:
    # Control what applications process metadata <TBD>

identity:
    # Control how identity information is collected:
    mac:
        port_set: all_ports 
    lldp:
        port_set: widget_tc_ports
    dns:
        port_set: all_ports
    dot1x:
        port_set: all_ports

port_sets:
    # Port Sets control what data plane ports policies and
    #  features are applied on:
    widget_tc_ports:
        - 'Switch 1':
            DPID: 8796751840564
            ports: 33,47-48
        - 'Switch 2':
            DPID: 0000000000002
            ports: 1-47
    guest_tc_ports:
        - 'Switch 1':
            DPID: 8796751840564
            ports: 1-32,34-46
    all_ports:
        - 'Any Switch':
            DPID: any
            ports: any

groups:
    Widget_IP_Intranet_group:
        comment: Example.com Intranet Servers
        ip_space: 192.168.56.12, 192.168.57.0/24, 10.0.2.15-10.0.2.19   
        
    Widget_Legacy_App_TCP_group:
        comment: Example.com Widget Legacy TCP ports
        transport_space: 5567, 40001-45641

    HTTP_TCP_group:
        comment: Standard HTTP TCP ports
        transport_space: 80,443,8080    
preflow:
    # Flow types to pre-install for performance:
    # <TBD>
```

Sub issues:
* Issue TBD introduces a negative match type: *none*
