### ISSUE TITLE
Traffic classification policy logic not working correctly for multiple terms

### ISSUE THREAD

**Issue by mattjhayes** [mattjhayes/nmeta#42]
Where the conditions_list match_type is set to 'all' it is still evaluated as an 'any'

Example (snippet from the main_policy.yaml):

```YAML
        - comment: Audit Division SSH traffic
          match_type: all
          conditions_list:
              - match_type: any
                tcp_src: 22
                tcp_dst: 22
              - match_type: any
                identity_lldp_systemname_re: '.*\.audit\.example\.com'
          actions:
              set_qos_tag: QoS_treatment=high_priority
              set_desc_tag: description="High Priority Audit Division SSH Traffic"
```
This example matches any tcp-22 traffic, but should only match when the identity also matches.

Work is required on updating the automated tests as they didn't pick this bug up.
